# Generated by Django 2.2.5 on 2019-10-02 15:15

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.IntegerField()),
                ('Size_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sub_categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_categorie', models.CharField(max_length=100)),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='under_subcategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Under_subcategorie', models.CharField(max_length=100)),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.categorie')),
                ('Sub_categorie', smart_selects.db_fields.GroupedForeignKey(group_field='Categorie', on_delete=django.db.models.deletion.CASCADE, to='datas.sub_categorie')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=100)),
                ('Country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.country')),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=100)),
                ('Country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.country')),
                ('State_id', smart_selects.db_fields.GroupedForeignKey(group_field='Country_id', on_delete=django.db.models.deletion.CASCADE, to='datas.state')),
            ],
        ),
    ]
