# Generated by Django 2.2.5 on 2019-10-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='Image',
        ),
    ]
