# Generated by Django 2.2.5 on 2019-10-02 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_or_Name', models.CharField(max_length=100)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.brand')),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.categorie')),
                ('Sub_categorie', smart_selects.db_fields.GroupedForeignKey(group_field='Categorie', on_delete=django.db.models.deletion.CASCADE, to='datas.sub_categorie')),
                ('Under_subcategorie', smart_selects.db_fields.GroupedForeignKey(group_field='Categorie', on_delete=django.db.models.deletion.CASCADE, to='datas.under_subcategorie')),
            ],
        ),
        migrations.CreateModel(
            name='product_varient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='pics')),
                ('Stock', models.IntegerField()),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.color')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.product')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.size')),
            ],
        ),
        migrations.CreateModel(
            name='promo_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=20)),
                ('Min_rate_for_apply', models.IntegerField()),
                ('Discount_persentage', models.IntegerField()),
                ('Max_discount_amount', models.IntegerField()),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_varient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.product_varient')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='shipping_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('House_no', models.CharField(max_length=100)),
                ('Land_mark', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('Phone', models.CharField(max_length=100)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.country')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.district')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.state')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='selled_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_item_sell', models.IntegerField()),
                ('Product_varient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.product_varient')),
            ],
        ),
        migrations.CreateModel(
            name='sell_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_items_selled', models.IntegerField()),
                ('Product_varient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.product_varient')),
            ],
        ),
        migrations.CreateModel(
            name='promo_code_applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.product')),
                ('Promo_code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.promo_code')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='promo_code_applicable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.product')),
                ('Promo_code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.promo_code')),
            ],
        ),
        migrations.CreateModel(
            name='prodect_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='pics')),
                ('Product_varient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.product_varient')),
            ],
        ),
        migrations.CreateModel(
            name='latest_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_varient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.product_varient')),
            ],
        ),
        migrations.CreateModel(
            name='header_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='pics')),
                ('About', models.TextField()),
                ('Product_varient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.product_varient')),
            ],
        ),
        migrations.CreateModel(
            name='conformation_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Refer_code', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('Date', models.DateField()),
                ('Delivered', models.BooleanField(default=False)),
                ('Received', models.BooleanField(default=False)),
                ('Return_req', models.BooleanField(default=False)),
                ('Address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.shipping_address')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='divisima.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='Product_varient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.product_varient'),
        ),
        migrations.AddField(
            model_name='cart',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
