# Generated by Django 2.2.5 on 2019-10-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisima', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conformation_tb',
            old_name='cost',
            new_name='Cost',
        ),
        migrations.RenameField(
            model_name='conformation_tb',
            old_name='items',
            new_name='Items',
        ),
    ]
