# Generated by Django 2.2.5 on 2019-10-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisima', '0002_auto_20191002_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='selled_items',
        ),
    ]
