# Generated by Django 2.2.5 on 2019-10-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisima', '0003_delete_selled_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping_address',
            old_name='Country',
            new_name='Country_id',
        ),
    ]
