# Generated by Django 2.2.5 on 2019-10-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisima', '0004_auto_20191003_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping_address',
            old_name='District',
            new_name='District_id',
        ),
        migrations.RenameField(
            model_name='shipping_address',
            old_name='State',
            new_name='State_id',
        ),
    ]
