# Generated by Django 2.2.5 on 2019-10-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisima', '0005_auto_20191003_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping_address',
            old_name='Country_id',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='shipping_address',
            old_name='District_id',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='shipping_address',
            old_name='State_id',
            new_name='State',
        ),
    ]
