# Generated by Django 2.2.5 on 2019-10-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisima', '0006_auto_20191003_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_varient',
            name='Sells',
            field=models.IntegerField(default=True),
        ),
    ]
