# Generated by Django 2.2.5 on 2019-10-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisima', '0007_product_varient_sells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_varient',
            name='Sells',
            field=models.IntegerField(default=0),
        ),
    ]
