# Generated by Django 2.2.5 on 2019-10-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisima', '0008_auto_20191003_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='promo_code_applicable_for_total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisima.promo_code')),
            ],
        ),
        migrations.DeleteModel(
            name='sell_details',
        ),
    ]
