# Generated by Django 2.2.5 on 2019-10-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisima', '0009_auto_20191003_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_code_applicable',
            name='Applicable_for_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promo_code_applicable',
            name='Product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisima.product'),
        ),
    ]
