# Generated by Django 2.2.5 on 2019-10-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisima', '0010_auto_20191004_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='promo_code_applicable_for_total',
        ),
    ]
